Больше деталей
htmlacademy-univer-javascript-1/2433947-kekstagram-4 pull request #3
Opened 2023-10-16 11:11 UTC by vvvyat

2023-10-16 11:31 UTC, Safyann requested changes

2023-10-16 11:31 UTC, Safyann commented on js/main.js
> +const photoDescriptions = Array.from({length: 25}, generatePhotoDescription);
переделай в функцию чтобы можно было вызвать

2023-10-16 12:25 UTC, Safyann requested changes

2023-10-16 12:25 UTC, Safyann commented on js/main.js
> +const getPhotoDescriptions = () => Array.from({length: 25}, generatePhotoDescription);
переделай в функцию чтобы можно было вызвать

2023-10-16 17:31 UTC, vvvyat commented on js/main.js
> +const getPhotoDescriptions = () => Array.from({length: 25}, generatePhotoDescription);
Я немного не понимаю что именно нужно изменить, это же и так стрелочная функция?

2023-10-17 16:28 UTC, vvvyat commented on js/main.js
> +const getPhotoDescriptions = () => Array.from({length: 25}, generatePhotoDescription);
> переделай в функцию чтобы можно было вызвать

Я немного не понимаю что именно нужно изменить, это же и так стрелочная функция?

2023-10-23 06:22 UTC, merged